"""Streamlit dashboard. Start it with ``obml dashboard``."""

from __future__ import annotations

import os
from pathlib import Path

import altair as alt
import pandas as pd
import streamlit as st

from orderbook_ml.config import Workspace
from orderbook_ml.dashboard.data import (
    WorkspaceData,
    apply_thresholds,
    candidates_table,
    depth_frame,
    discover_workspaces,
    importance_frame,
    load_workspace,
    stream_state,
)
from orderbook_ml.features import FEATURE_GROUPS
from orderbook_ml.status import pipeline_status

SIGNAL_COLORS = {"BUY": "#16a34a", "HOLD": "#64748b", "SELL": "#dc2626"}
BADGE_COLORS = {"BUY": "green", "HOLD": "gray", "SELL": "red"}

st.set_page_config(
    page_title="Order Book Signal Monitor",
    page_icon=":material/candlestick_chart:",
    layout="wide",
)


# --------------------------------------------------------------------------- sidebar


def sidebar() -> tuple[Path, float, float, int, bool, int]:
    default_root = Path(os.getenv("OBML_DATA_DIR", "data"))
    options = discover_workspaces(default_root)
    # Prefer a workspace that already has results so first-time users land on something useful.
    with_results = [p for p in options if (p / "predictions" / "live.parquet").exists()]
    default_index = options.index(with_results[0]) if with_results else 0

    st.sidebar.header("Settings")
    root = st.sidebar.selectbox(
        "Workspace",
        options,
        index=default_index,
        format_func=lambda p: str(p),
        help="Folder holding snapshots, models and predictions. `obml demo` creates data/demo.",
    )
    session = load_workspace(root).session or {}

    st.sidebar.subheader("Signal thresholds")
    sell, buy = st.sidebar.slider(
        "HOLD zone for P(up)",
        min_value=0.05,
        max_value=0.95,
        value=(
            float(session.get("sell_threshold", 0.40)),
            float(session.get("buy_threshold", 0.60)),
        ),
        step=0.01,
        help="SELL at or below the lower bound, BUY at or above the upper bound, HOLD between.",
    )
    window = st.sidebar.slider(
        "Snapshots shown",
        min_value=50,
        max_value=600,
        value=300,
        step=50,
        help="How many of the most recent predictions to plot (10 per second at 100 ms).",
    )
    st.sidebar.subheader("Refresh")
    auto = st.sidebar.toggle("Auto-refresh", value=True)
    every = st.sidebar.select_slider(
        "Every (seconds)", options=[1, 2, 5, 10, 30], value=2, disabled=not auto
    )
    st.sidebar.divider()
    st.sidebar.caption(
        "Research tool, not financial advice. Signals ignore fees, latency and slippage."
    )
    return root, sell, buy, window, auto, every


# --------------------------------------------------------------------------- header


def header(data: WorkspaceData) -> None:
    symbol = data.symbol or "the market"
    horizon = data.horizon_sec or 1
    st.title("Order Book Signal Monitor")
    st.markdown(
        f"Reads the live **limit order book** of **{symbol}**, estimates the probability that "
        f"the price will **tick up within the next {horizon} second(s)**, and turns it into a "
        "**BUY / HOLD / SELL** signal."
    )
    if data.synthetic:
        st.info(
            "**Synthetic data.** This workspace was generated by the built-in simulator "
            "(`obml demo`), whose price moves are designed to be partly predictable. It shows "
            "how the system works - not how it would perform on a real market.",
            icon=":material/science:",
        )
    for error in data.errors:
        st.error(error, icon=":material/error:")


# --------------------------------------------------------------------------- onboarding


def onboarding(workspace: Workspace) -> None:
    st.subheader("Get started")
    st.markdown(
        "Nothing to show in this workspace yet. The fastest way to see the dashboard in action "
        "is the offline demo - it simulates an order book, trains a model and scores an "
        "unseen session in about a minute:"
    )
    st.code("obml demo\nobml dashboard", language="bash")
    st.markdown("Or work through the pipeline on real Binance data:")
    for i, step in enumerate(pipeline_status(workspace), 1):
        icon = ":material/check_circle:" if step.done else ":material/radio_button_unchecked:"
        optional = " *(optional)*" if step.optional else ""
        with st.container(border=True):
            st.markdown(f"{icon} **{i}. {step.title}**{optional}  \n{step.description}")
            if step.done:
                st.caption(step.detail or "Done")
            else:
                st.code(step.command, language="bash")


# --------------------------------------------------------------------------- charts


def _time_axis() -> alt.X:
    return alt.X("timestamp:T", title=None, axis=alt.Axis(format="%H:%M:%S", labelOverlap=True))


def price_chart(df: pd.DataFrame) -> alt.Chart:
    base = alt.Chart(df).encode(x=_time_axis())
    line = base.mark_line(color="#2563eb", strokeWidth=1.6).encode(
        y=alt.Y("mid_price:Q", title="Mid price", scale=alt.Scale(zero=False)),
        tooltip=[
            alt.Tooltip("timestamp:T", format="%H:%M:%S.%L"),
            alt.Tooltip("mid_price:Q", format=",.2f"),
            alt.Tooltip("spread:Q", format=",.4f"),
            "signal:N",
        ],
    )
    changes = df[df["signal"] != df["signal"].shift()]
    marks = (
        alt.Chart(changes[changes["signal"] != "HOLD"])
        .mark_point(filled=True, size=70)
        .encode(
            x="timestamp:T",
            y="mid_price:Q",
            shape=alt.Shape(
                "signal:N",
                scale=alt.Scale(domain=["BUY", "SELL"], range=["triangle-up", "triangle-down"]),
                legend=None,
            ),
            color=alt.Color(
                "signal:N",
                scale=alt.Scale(domain=list(SIGNAL_COLORS), range=list(SIGNAL_COLORS.values())),
                legend=alt.Legend(orient="top", title="New signal"),
            ),
            tooltip=[
                alt.Tooltip("timestamp:T", format="%H:%M:%S.%L"),
                "signal:N",
                alt.Tooltip("prob_up:Q", format=".3f"),
            ],
        )
    )
    return (line + marks).properties(height=280)


def probability_chart(df: pd.DataFrame, sell: float, buy: float) -> alt.Chart:
    bands = pd.DataFrame(
        [
            {"low": buy, "high": 1.0, "zone": "BUY"},
            {"low": sell, "high": buy, "zone": "HOLD"},
            {"low": 0.0, "high": sell, "zone": "SELL"},
        ]
    )
    zone = (
        alt.Chart(bands)
        .mark_rect(opacity=0.10)
        .encode(
            y=alt.Y("low:Q", scale=alt.Scale(domain=[0, 1])),
            y2="high:Q",
            color=alt.Color(
                "zone:N",
                scale=alt.Scale(domain=list(SIGNAL_COLORS), range=list(SIGNAL_COLORS.values())),
                legend=alt.Legend(orient="top", title="Zone"),
            ),
        )
    )
    line = (
        alt.Chart(df)
        .mark_line(color="#7c3aed", strokeWidth=1.6)
        .encode(
            x=_time_axis(),
            y=alt.Y("prob_up:Q", title="P(price goes up)", scale=alt.Scale(domain=[0, 1])),
            tooltip=[
                alt.Tooltip("timestamp:T", format="%H:%M:%S.%L"),
                alt.Tooltip("prob_up:Q", format=".3f"),
                "signal:N",
            ],
        )
    )
    return (zone + line).properties(height=280)


def imbalance_chart(df: pd.DataFrame) -> alt.Chart:
    long = df.melt(
        id_vars="timestamp",
        value_vars=["obi_level_1", "obi_level_5", "decayed_obi"],
        var_name="measure",
        value_name="imbalance",
    )
    long["measure"] = long["measure"].map(
        {"obi_level_1": "Top level", "obi_level_5": "Top 5 levels", "decayed_obi": "Depth-weighted"}
    )
    zero = (
        alt.Chart(pd.DataFrame({"y": [0]}))
        .mark_rule(color="#94a3b8", strokeDash=[4, 4])
        .encode(y="y:Q")
    )
    lines = (
        alt.Chart(long)
        .mark_line(strokeWidth=1.3)
        .encode(
            x=_time_axis(),
            y=alt.Y(
                "imbalance:Q", title="Imbalance (+ = buy side)", scale=alt.Scale(domain=[-1, 1])
            ),
            color=alt.Color("measure:N", legend=alt.Legend(orient="top", title=None)),
            tooltip=[
                alt.Tooltip("timestamp:T", format="%H:%M:%S.%L"),
                "measure:N",
                alt.Tooltip("imbalance:Q", format="+.3f"),
            ],
        )
    )
    return (zero + lines).properties(height=260)


def depth_chart(book: dict) -> alt.Chart | None:
    df = depth_frame(book)
    if df.empty:
        return None
    return (
        alt.Chart(df)
        .mark_area(interpolate="step-after", opacity=0.45, line=True)
        .encode(
            x=alt.X("price:Q", title="Price", scale=alt.Scale(zero=False)),
            y=alt.Y("cumulative:Q", title="Cumulative quantity"),
            color=alt.Color(
                "side:N",
                scale=alt.Scale(domain=["Bids", "Asks"], range=["#16a34a", "#dc2626"]),
                legend=alt.Legend(orient="top", title=None),
            ),
            tooltip=[
                alt.Tooltip("price:Q", format=",.2f"),
                "side:N",
                alt.Tooltip("quantity:Q", format=",.4f"),
                alt.Tooltip("cumulative:Q", format=",.4f"),
            ],
        )
        .properties(height=260)
    )


# --------------------------------------------------------------------------- tabs


def live_tab(root: Path, sell: float, buy: float, window: int) -> None:
    data = load_workspace(root)
    if not data.has_predictions or data.live is None:
        st.info(
            "No predictions yet. Start scoring with `obml predict` (live) or "
            "`obml predict --replay <dir> --realtime`, then this page updates by itself.",
            icon=":material/hourglass_empty:",
        )
        return

    live = apply_thresholds(data.live, buy, sell).tail(window)
    latest, first = live.iloc[-1], live.iloc[0]
    state, color = stream_state(data)
    horizon = data.horizon_sec or 1

    top = st.columns([3, 1])
    top[0].badge(state, color=color)  # type: ignore[arg-type]
    top[0].caption(
        f"Last update {latest['timestamp']:%Y-%m-%d %H:%M:%S} UTC · "
        f"median scoring time {live['latency_ms'].median():.1f} ms per snapshot"
    )

    k1, k2, k3, k4, k5 = st.columns(5)
    k1.metric(
        "Mid price",
        f"{latest['mid_price']:,.2f}",
        delta=f"{latest['mid_price'] - first['mid_price']:+,.2f} in window",
        delta_color="off",
        delta_arrow="off",
        border=True,
    )
    k2.metric(
        "Bid-ask spread",
        f"{latest['spread']:,.4g}",
        border=True,
        help="Gap between the best sell and best buy price.",
    )
    obi = float(latest["obi_level_5"])
    k3.metric(
        "Imbalance (top 5)",
        f"{obi:+.2f}",
        delta="buy-side heavy" if obi > 0.05 else "sell-side heavy" if obi < -0.05 else "balanced",
        delta_color="normal" if abs(obi) > 0.05 else "off",
        delta_arrow="auto" if abs(obi) > 0.05 else "off",
        border=True,
        help="(bid volume - ask volume) / total volume over the best 5 levels.",
    )
    k4.metric(
        f"P(up in {horizon}s)",
        f"{latest['prob_up']:.1%}",
        delta=f"{latest['prob_up'] - live['prob_up'].iloc[-2]:+.1%}" if len(live) > 1 else None,
        border=True,
        help="Model probability that the mid price is higher after the horizon.",
    )
    with k5.container(border=True):
        st.caption("Signal")
        st.badge(f"**{latest['signal']}**", color=BADGE_COLORS[latest["signal"]])  # type: ignore[arg-type]
        counts = live["signal"].value_counts(normalize=True)
        st.caption(" · ".join(f"{s} {counts.get(s, 0):.0%}" for s in SIGNAL_COLORS))

    left, right = st.columns(2)
    with left:
        st.markdown("**Price and signal changes**")
        st.altair_chart(price_chart(live), width="stretch")
        st.markdown("**Order book imbalance**")
        st.altair_chart(imbalance_chart(live), width="stretch")
    with right:
        st.markdown("**Model probability and signal zones**")
        st.altair_chart(probability_chart(live, sell, buy), width="stretch")
        st.markdown("**Current order book depth**")
        chart = depth_chart(data.book) if data.book else None
        if chart is None:
            st.caption("Depth snapshot not available yet.")
        else:
            st.altair_chart(chart, width="stretch")

    with st.expander("Recent predictions"):
        table = live.iloc[::-1].head(200)[
            ["timestamp", "mid_price", "spread", "obi_level_5", "prob_up", "signal", "latency_ms"]
        ]
        st.dataframe(
            table,
            hide_index=True,
            column_config={
                "timestamp": st.column_config.DatetimeColumn("Time (UTC)", format="HH:mm:ss.SSS"),
                "mid_price": st.column_config.NumberColumn("Mid", format="%.2f"),
                "spread": st.column_config.NumberColumn("Spread", format="%.4f"),
                "obi_level_5": st.column_config.NumberColumn("Imbalance", format="%+.3f"),
                "prob_up": st.column_config.ProgressColumn(
                    "P(up)", min_value=0, max_value=1, format="%.3f"
                ),
                "signal": "Signal",
                "latency_ms": st.column_config.NumberColumn("Scoring ms", format="%.1f"),
            },
            height=320,
        )


def model_tab(data: WorkspaceData) -> None:
    training = data.training
    if not training:
        st.info(
            "No trained model yet. Run `obml build-dataset` then `obml train`.",
            icon=":material/model_training:",
        )
        return
    champion = training["candidates"][training["selected_model"]]
    test = champion["test"]

    st.markdown(
        f"**{champion['display_name']}** predicts `{training['target']}` "
        f"(price up after {training['horizon_sec']}s). It was chosen among "
        f"{len(training['candidates'])} candidates by {training['selection_rule']}; "
        "the figures below are on the held-out **test** period it never saw."
    )
    c1, c2, c3, c4 = st.columns(4)
    c1.metric(
        "ROC-AUC",
        f"{test['auc']:.3f}" if test["auc"] is not None else "n/a",
        delta=f"{test['auc'] - 0.5:+.3f} vs coin flip" if test["auc"] else None,
        border=True,
        help="0.5 = no skill, 1.0 = perfect ranking of up vs not-up moves.",
    )
    c2.metric(
        "Log loss",
        f"{test['log_loss']:.4f}",
        delta=f"{test['log_loss'] - test['baseline_log_loss']:+.4f} vs baseline",
        delta_color="inverse",
        border=True,
        help="Lower is better. Baseline always predicts the historical up-rate.",
    )
    c3.metric(
        "Accuracy",
        f"{test['accuracy']:.1%}",
        delta=f"{test['accuracy'] - max(test['positive_rate'], 1 - test['positive_rate']):+.1%}"
        " vs majority class",
        border=True,
    )
    c4.metric(
        "Up moves in test",
        f"{test['positive_rate']:.1%}",
        help="Share of test rows where the price actually went up.",
        border=True,
    )

    st.markdown("**All candidates**")
    st.dataframe(
        candidates_table(training),
        hide_index=True,
        width="stretch",
        column_config={"Selected": st.column_config.CheckboxColumn()},
    )

    left, right = st.columns(2)
    with left:
        st.markdown("**Calibration (test)** - do predicted probabilities match reality?")
        rows = [
            {**b, "model": r["display_name"]}
            for r in training["candidates"].values()
            for b in r["test"]["calibration"]
        ]
        calib = pd.DataFrame(rows)
        diagonal = (
            alt.Chart(pd.DataFrame({"x": [0, 1], "y": [0, 1]}))
            .mark_line(strokeDash=[4, 4], color="#94a3b8")
            .encode(x="x:Q", y="y:Q")
        )
        points = (
            alt.Chart(calib)
            .mark_line(point=True)
            .encode(
                x=alt.X(
                    "mean_predicted:Q", title="Predicted P(up)", scale=alt.Scale(domain=[0, 1])
                ),
                y=alt.Y(
                    "observed_rate:Q", title="Observed up-rate", scale=alt.Scale(domain=[0, 1])
                ),
                color=alt.Color("model:N", legend=alt.Legend(orient="top", title=None)),
                tooltip=[
                    "model:N",
                    "bin:N",
                    "count:Q",
                    alt.Tooltip("observed_rate:Q", format=".3f"),
                ],
            )
        )
        st.altair_chart((diagonal + points).properties(height=300), width="stretch")
    with right:
        imp, source = importance_frame(data)
        st.markdown(f"**What drives the prediction** - {source.lower()}")
        st.altair_chart(
            alt.Chart(imp)
            .mark_bar(color="#2563eb")
            .encode(
                x=alt.X("importance:Q", title=None),
                y=alt.Y(
                    "feature:N",
                    sort="-x",
                    title=None,
                    axis=alt.Axis(labelLimit=220, labelOverlap=False),
                ),
                tooltip=["feature:N", alt.Tooltip("importance:Q", format=".4f")],
            )
            .properties(height=max(120, 20 * len(imp))),
            width="stretch",
        )

    cm = test["confusion_matrix"]
    with st.expander("Confusion matrix (threshold 0.5)"):
        st.dataframe(
            pd.DataFrame(
                cm,
                index=["Actually not up", "Actually up"],
                columns=["Predicted not up", "Predicted up"],
            ),
        )
    shap_png = data.workspace.reports / "shap_summary.png"
    if shap_png.exists():
        with st.expander("SHAP summary plot"):
            st.image(str(shap_png))
    card = data.workspace.reports / "model_card.md"
    if card.exists():
        with st.expander("Model card"):
            st.markdown(card.read_text(encoding="utf-8"))


def quality_tab(data: WorkspaceData) -> None:
    q = data.quality
    if not q:
        st.info(
            "No data-quality report yet. Run `obml validate` or `obml build-dataset`.",
            icon=":material/fact_check:",
        )
        return
    c1, c2, c3, c4 = st.columns(4)
    c1.metric(
        "Quality score",
        f"{q['quality_score']:.1f}%",
        border=True,
        help="Share of snapshots that are valid and not preceded by a gap.",
    )
    c2.metric(
        "Snapshots",
        f"{q['total_snapshots']:,}",
        border=True,
        help=f"{q['duration_sec'] / 60:.1f} minutes of data",
    )
    c3.metric(
        "Gaps > 200 ms",
        f"{q['timestamp_gaps']:,}",
        border=True,
        help=f"Largest gap: {q['largest_gap_sec']}s",
    )
    c4.metric("Crossed / empty books", f"{q['crossed_books'] + q['empty_sides']:,}", border=True)
    st.caption(
        f"{q['symbol']} · {q['start']} → {q['end']} · median interval "
        f"{q['median_interval_ms']} ms · spread outliers {q['spread_outliers']}"
    )
    png = data.workspace.reports / "data_quality.png"
    if png.exists():
        st.image(str(png))


def about_tab() -> None:
    st.markdown(
        """
### What am I looking at?

Every exchange keeps an **order book**: a list of people waiting to **buy** (bids) and
**sell** (asks) at different prices. When far more volume is waiting on the buy side than
on the sell side, the price is somewhat more likely to tick up next, and vice versa.

This project records the Binance order book ten times per second, turns each snapshot into
measurements of that pressure (imbalance, spread, depth shape, recent momentum), and trains
a machine-learning model to estimate **the probability that the price will be higher a
moment from now**.

| Signal | Meaning |
|---|---|
| **BUY** | P(up) is at or above the upper threshold |
| **HOLD** | the model is not confident either way |
| **SELL** | P(up) is at or below the lower threshold |

Thresholds are adjustable in the sidebar; changing them re-labels past signals instantly
without retraining.

### How to read the model numbers

* **ROC-AUC** measures how well the model ranks moments that went up above moments that
  didn't: 0.5 is a coin flip. In real, liquid markets values only slightly above 0.5 are
  typical and still meaningful.
* **Log loss vs baseline** shows whether the probabilities beat simply predicting the
  historical up-rate every time.

### Caveats

Signals are research output, not trading advice: they ignore fees, latency, queue position
and slippage.
"""
    )
    st.markdown("### Features used by the model")
    cols = st.columns(3)
    for i, (group, names) in enumerate(FEATURE_GROUPS.items()):
        with cols[i % 3]:
            st.markdown(f"**{group}**  \n" + "  \n".join(f"`{n}`" for n in names))


# --------------------------------------------------------------------------- main


def main() -> None:
    root, sell, buy, window, auto, every = sidebar()
    data = load_workspace(root)
    header(data)

    if not data.has_predictions and not data.training:
        onboarding(data.workspace)
        return

    live, model, quality, about = st.tabs(
        ["Live signal", "Model performance", "Data quality", "How it works"]
    )
    with live:
        st.fragment(run_every=every if auto else None)(live_tab)(root, sell, buy, window)
    with model:
        model_tab(data)
    with quality:
        quality_tab(data)
    with about:
        about_tab()


main()
